import { GDPEntry } from './page';

export const countryData: GDPEntry[] = [
  {
    Country: 'United States',
    Ranking: '1',
    'Real GDP (Billion $)': '21427.7',
    Industries: 'Technology, Finance, Healthcare',
    latitude: 39.8283,
    longitude: -98.5795,
  },
  {
    Country: 'China',
    Ranking: '2',
    'Real GDP (Billion $)': '14342.6',
    Industries: 'Manufacturing, Technology, Agriculture',
    latitude: 35.8617,
    longitude: 104.1954,
  },
  {
    Country: 'Japan',
    Ranking: '3',
    'Real GDP (Billion $)': '5081.8',
    Industries: 'Automotive, Electronics, Machinery',
    latitude: 36.2048,
    longitude: 138.2529,
  },
  {
    Country: 'Germany',
    Ranking: '4',
    'Real GDP (Billion $)': '4259.9',
    Industries: 'Automotive, Machinery, Chemicals',
    latitude: 51.1657,
    longitude: 10.4515,
  },
  {
    Country: 'India',
    Ranking: '5',
    'Real GDP (Billion $)': '3176.3',
    Industries: 'IT Services, Textiles, Pharmaceuticals',
    latitude: 20.5937,
    longitude: 78.9629,
  },
  {
    Country: 'United Kingdom',
    Ranking: '6',
    'Real GDP (Billion $)': '2827.1',
    Industries: 'Finance, Technology, Manufacturing',
    latitude: 55.3781,
    longitude: -3.436,
  },
  {
    Country: 'France',
    Ranking: '7',
    'Real GDP (Billion $)': '2715.5',
    Industries: 'Aerospace, Automotive, Pharmaceuticals',
    latitude: 46.6034,
    longitude: 1.8883,
  },
  {
    Country: 'Italy',
    Ranking: '8',
    'Real GDP (Billion $)': '2001.2',
    Industries: 'Fashion, Automotive, Machinery',
    latitude: 41.8719,
    longitude: 12.5674,
  },
  {
    Country: 'Canada',
    Ranking: '9',
    'Real GDP (Billion $)': '1840.3',
    Industries: 'Natural Resources, Technology, Manufacturing',
    latitude: 56.1304,
    longitude: -106.3468,
  },
  {
    Country: 'South Korea',
    Ranking: '10',
    'Real GDP (Billion $)': '1640.4',
    Industries: 'Electronics, Automotive, Shipbuilding',
    latitude: 35.9078,
    longitude: 127.7669,
  },
  {
    Country: 'Australia',
    Ranking: '11',
    'Real GDP (Billion $)': '1392.7',
    Industries: 'Mining, Agriculture, Services',
    latitude: -25.2744,
    longitude: 133.7751,
  },
  {
    Country: 'Spain',
    Ranking: '12',
    'Real GDP (Billion $)': '1390.5',
    Industries: 'Tourism, Automotive, Agriculture',
    latitude: 40.4637,
    longitude: -3.7492,
  },
  {
    Country: 'Mexico',
    Ranking: '13',
    'Real GDP (Billion $)': '1265.5',
    Industries: 'Manufacturing, Agriculture, Services',
    latitude: 23.6345,
    longitude: -102.5528,
  },
  {
    Country: 'Indonesia',
    Ranking: '14',
    'Real GDP (Billion $)': '1050.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: -0.7893,
    longitude: 113.9213,
  },
  {
    Country: 'Netherlands',
    Ranking: '15',
    'Real GDP (Billion $)': '902.4',
    Industries: 'Agriculture, Technology, Trade',
    latitude: 52.1326,
    longitude: 5.2913,
  },
  {
    Country: 'Saudi Arabia',
    Ranking: '16',
    'Real GDP (Billion $)': '793.0',
    Industries: 'Oil, Petrochemicals, Mining',
    latitude: 23.8859,
    longitude: 45.0792,
  },
  {
    Country: 'Turkey',
    Ranking: '17',
    'Real GDP (Billion $)': '754.0',
    Industries: 'Textiles, Automotive, Electronics',
    latitude: 38.9637,
    longitude: 35.2433,
  },
  {
    Country: 'Switzerland',
    Ranking: '18',
    'Real GDP (Billion $)': '703.0',
    Industries: 'Finance, Pharmaceuticals, Machinery',
    latitude: 46.8182,
    longitude: 8.2275,
  },
  {
    Country: 'Taiwan',
    Ranking: '19',
    'Real GDP (Billion $)': '610.0',
    Industries: 'Electronics, Manufacturing, Services',
    latitude: 23.6978,
    longitude: 120.9605,
  },
  {
    Country: 'Sweden',
    Ranking: '20',
    'Real GDP (Billion $)': '600.0',
    Industries: 'Automotive, Telecommunications, Pharmaceuticals',
    latitude: 60.1282,
    longitude: 18.6435,
  },
  {
    Country: 'Belgium',
    Ranking: '21',
    'Real GDP (Billion $)': '590.0',
    Industries: 'Chemicals, Pharmaceuticals, Manufacturing',
    latitude: 50.8503,
    longitude: 4.3517,
  },
  {
    Country: 'Thailand',
    Ranking: '22',
    'Real GDP (Billion $)': '543.0',
    Industries: 'Agriculture, Manufacturing, Tourism',
    latitude: 15.87,
    longitude: 100.9925,
  },
  {
    Country: 'Norway',
    Ranking: '23',
    'Real GDP (Billion $)': '482.0',
    Industries: 'Oil, Shipping, Seafood',
    latitude: 60.472,
    longitude: 8.4689,
  },
  {
    Country: 'Austria',
    Ranking: '24',
    'Real GDP (Billion $)': '455.0',
    Industries: 'Machinery, Chemicals, Tourism',
    latitude: 47.5162,
    longitude: 14.5501,
  },
  {
    Country: 'Ireland',
    Ranking: '25',
    'Real GDP (Billion $)': '450.0',
    Industries: 'Pharmaceuticals, Technology, Finance',
    latitude: 53.4129,
    longitude: -8.2439,
  },
  {
    Country: 'Finland',
    Ranking: '26',
    'Real GDP (Billion $)': '300.0',
    Industries: 'Technology, Forestry, Manufacturing',
    latitude: 61.9241,
    longitude: 25.7482,
  },
  {
    Country: 'Czech Republic',
    Ranking: '27',
    'Real GDP (Billion $)': '290.0',
    Industries: 'Automotive, Machinery, Electronics',
    latitude: 49.8175,
    longitude: 15.473,
  },
  {
    Country: 'Portugal',
    Ranking: '28',
    'Real GDP (Billion $)': '280.0',
    Industries: 'Tourism, Agriculture, Textiles',
    latitude: 39.3999,
    longitude: -8.2245,
  },
  {
    Country: 'New Zealand',
    Ranking: '29',
    'Real GDP (Billion $)': '270.0',
    Industries: 'Agriculture, Tourism, Manufacturing',
    latitude: -40.9006,
    longitude: 174.886,
  },
  {
    Country: 'South Africa',
    Ranking: '30',
    'Real GDP (Billion $)': '350.0',
    Industries: 'Mining, Agriculture, Manufacturing',
    latitude: -30.5595,
    longitude: 22.9375,
  },
  {
    Country: 'Malaysia',
    Ranking: '31',
    'Real GDP (Billion $)': '350.0',
    Industries: 'Electronics, Palm Oil, Manufacturing',
    latitude: 4.2105,
    longitude: 101.9758,
  },
  {
    Country: 'Philippines',
    Ranking: '32',
    'Real GDP (Billion $)': '350.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 12.8797,
    longitude: 121.774,
  },
  {
    Country: 'Vietnam',
    Ranking: '33',
    'Real GDP (Billion $)': '340.0',
    Industries: 'Manufacturing, Agriculture, Services',
    latitude: 14.0583,
    longitude: 108.2772,
  },
  {
    Country: 'Bangladesh',
    Ranking: '34',
    'Real GDP (Billion $)': '330.0',
    Industries: 'Textiles, Agriculture, Services',
    latitude: 23.685,
    longitude: 90.3563,
  },
  {
    Country: 'Colombia',
    Ranking: '35',
    'Real GDP (Billion $)': '320.0',
    Industries: 'Agriculture, Mining, Manufacturing',
    latitude: 4.5709,
    longitude: -74.2973,
  },
  {
    Country: 'Chile',
    Ranking: '36',
    'Real GDP (Billion $)': '310.0',
    Industries: 'Mining, Agriculture, Services',
    latitude: -35.6751,
    longitude: -71.5375,
  },
  {
    Country: 'Romania',
    Ranking: '37',
    'Real GDP (Billion $)': '300.0',
    Industries: 'Automotive, IT, Agriculture',
    latitude: 45.9432,
    longitude: 24.9668,
  },
  {
    Country: 'Ukraine',
    Ranking: '38',
    'Real GDP (Billion $)': '290.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 48.3794,
    longitude: 31.1656,
  },
  {
    Country: 'Greece',
    Ranking: '39',
    'Real GDP (Billion $)': '280.0',
    Industries: 'Tourism, Shipping, Agriculture',
    latitude: 39.0742,
    longitude: 21.8243,
  },
  {
    Country: 'Iceland',
    Ranking: '40',
    'Real GDP (Billion $)': '270.0',
    Industries: 'Tourism, Fishing, Renewable Energy',
    latitude: 64.9631,
    longitude: -19.0208,
  },
  {
    Country: 'Serbia',
    Ranking: '41',
    'Real GDP (Billion $)': '260.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 44.0165,
    longitude: 21.0059,
  },
  {
    Country: 'Bulgaria',
    Ranking: '42',
    'Real GDP (Billion $)': '250.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 42.7339,
    longitude: 25.4858,
  },
  {
    Country: 'Slovakia',
    Ranking: '43',
    'Real GDP (Billion $)': '240.0',
    Industries: 'Automotive, Electronics, Services',
    latitude: 48.669,
    longitude: 19.699,
  },
  {
    Country: 'Croatia',
    Ranking: '44',
    'Real GDP (Billion $)': '230.0',
    Industries: 'Tourism, Agriculture, Manufacturing',
    latitude: 45.1,
    longitude: 15.2,
  },
  {
    Country: 'Estonia',
    Ranking: '45',
    'Real GDP (Billion $)': '220.0',
    Industries: 'Technology, Services, Manufacturing',
    latitude: 58.5953,
    longitude: 25.0136,
  },
  {
    Country: 'Latvia',
    Ranking: '46',
    'Real GDP (Billion $)': '210.0',
    Industries: 'Manufacturing, Services, Agriculture',
    latitude: 56.8796,
    longitude: 24.6032,
  },
  {
    Country: 'Lithuania',
    Ranking: '47',
    'Real GDP (Billion $)': '200.0',
    Industries: 'Manufacturing, Services, Agriculture',
    latitude: 55.1694,
    longitude: 23.8813,
  },
  {
    Country: 'Moldova',
    Ranking: '48',
    'Real GDP (Billion $)': '190.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 47.4116,
    longitude: 28.3699,
  },
  {
    Country: 'Armenia',
    Ranking: '49',
    'Real GDP (Billion $)': '180.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 40.0691,
    longitude: 45.0382,
  },
  {
    Country: 'Georgia',
    Ranking: '50',
    'Real GDP (Billion $)': '170.0',
    Industries: 'Agriculture, Manufacturing, Services',
    latitude: 42.3154,
    longitude: 43.3569,
  },
];
